import { NextResponse } from "next/server";
import { connectDB } from "@/lib/mongodb";
import Member from "@/models/Member";

// Admin-only seed endpoint
export async function POST(req: Request) {
  try {
    // Simple authentication check
    const { password } = await req.json();
    if (password !== process.env.ADMIN_PASSWORD) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    await connectDB();

    // Clear existing data
    await Member.deleteMany({});

    // Seed data with actual member photos from uploads (names matched with photo files)
    const members = [
      {
        membershipNo: "M No.822",
        firstName: "Aftab",
        lastName: "Bhanbhro",
        fatherName: "Muhammad Ali",
        cnic: "42201-1234567-8",
        phone: "0300-1234567",
        email: "",
        ntn: "",
        address: "Khairpur City",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Aftab Bhanbhro pic.jpg",
      },
      {
        membershipNo: "M No.823",
        firstName: "Arsalan",
        lastName: "Ali",
        fatherName: "Ghulam Ali",
        cnic: "42202-2345678-9",
        phone: "0321-2345678",
        email: "",
        ntn: "",
        address: "Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Arsalan Ali pic.jpg",
      },
      {
        membershipNo: "M No.824",
        firstName: "Badar",
        lastName: "Hussain",
        fatherName: "Muhammad Saflar Tunio",
        cnic: "45208-9576753-9",
        phone: "0332-2743529",
        email: "",
        ntn: "",
        address: "Goth Ali Mardan Tunio, p/o Hangorja, Peer Meshaikh, Tehsil Sohbo Dero, District Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Badar Hussain pic.jpg",
      },
      {
        membershipNo: "M No.825",
        firstName: "Dawood",
        lastName: "Bhuto",
        fatherName: "Muhammad Bhutto",
        cnic: "45208-3977675-9",
        phone: "0300-3125240",
        email: "",
        ntn: "",
        address: "Goth Raseman, Hangorja, Tehsil Sohbo dero District Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "Chairman Sukkur Division",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Dawood Bhuto pic.jpg",
      },
      {
        membershipNo: "M No.826",
        firstName: "Feroz",
        lastName: "Gull",
        fatherName: "Gulzar Ali",
        cnic: "42201-1276563-3",
        phone: "0307-5165715",
        email: "",
        ntn: "",
        address: "Kot Pir Bux Metlo Post Office Karlu Mori Shah Ladhat Tehsil & District Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Feroz Gull pic.jpg",
      },
      {
        membershipNo: "M No.827",
        firstName: "Ghulam Sarwar",
        lastName: "Markhand",
        fatherName: "Hafiz Abdul Rahman Markhand",
        cnic: "42203-0426908-9",
        phone: "0333-7594897",
        email: "",
        ntn: "",
        address: "Bungalow # C-5, Mumtaz Colony, Khairpur (Mirs), Sindh",
        district: "Khairpur",
        businessName: "",
        businessType: "Honorary Member",
        membershipCategory: "Honorary Member",
        fee: 0,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Ghulam Sarwar Markhand pic.jpg",
      },
      {
        membershipNo: "M No.828",
        firstName: "Gulsher",
        lastName: "Ahmad",
        fatherName: "",
        cnic: "45208-2183676-5",
        phone: "0325-3441342",
        email: "",
        ntn: "",
        address: "Sobhodero Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Student",
        fee: 0,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Gulsher Ahmad pic.jpg",
      },
      {
        membershipNo: "M No.829",
        firstName: "Hassan",
        lastName: "Raza",
        fatherName: "Rahim Bux",
        cnic: "42209-8087184-1",
        phone: "0325-9260227",
        email: "",
        ntn: "",
        address: "Kot Khuda Bux Bhanbhro soho Tehsil Kot Diji, District Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "Advocate, General Secretary Kot Diji",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Hassan Raza pic.jpg",
      },
      {
        membershipNo: "M No.830",
        firstName: "Imran",
        lastName: "",
        fatherName: "Qalandar Bux Bhanbhro",
        cnic: "42205-1587267-7",
        phone: "0301-3513283",
        email: "",
        ntn: "",
        address: "Sarai Muhammad Bux Kot Diji District Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "President Tehsil Kot Diji",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Imran pic.jpg",
      },
      {
        membershipNo: "M No.831",
        firstName: "Khair",
        lastName: "Muhammad",
        fatherName: "Akhtar Ali",
        cnic: "42206-6789012-3",
        phone: "0301-6789012",
        email: "",
        ntn: "",
        address: "New Town, Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Khair muhammad pic.jpg",
      },
      {
        membershipNo: "M No.832",
        firstName: "M",
        lastName: "Hayat",
        fatherName: "Muhammad Yousaf Tanwari",
        cnic: "45302-8306730-3",
        phone: "0334-2427022",
        email: "",
        ntn: "",
        address: "Near Higher Secondary School National Hiway, Mohallah Tanwari Hango Taraf Kili Sobodero District Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/M Hayat pic.jpg",
      },
      {
        membershipNo: "M No.833",
        firstName: "Mir Hassan",
        lastName: "Bhanbhro",
        fatherName: "Ali Bhanbhro",
        cnic: "42203-3456789-0",
        phone: "0333-3456789",
        email: "",
        ntn: "",
        address: "Station Road, Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Mir Hassan Bhanbhro pic.jpg",
      },
      {
        membershipNo: "M No.834",
        firstName: "Muhammad",
        lastName: "Ranjhan",
        fatherName: "Fazal Ahmed",
        cnic: "42205-5678901-2",
        phone: "0312-5678901",
        email: "",
        ntn: "",
        address: "Hospital Road, Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Muhammad Ranjhan pic.jpg",
      },
      {
        membershipNo: "M No.835",
        firstName: "Rashid",
        lastName: "Hussian",
        fatherName: "Ghulam Hussain",
        cnic: "42204-4567890-1",
        phone: "0345-4567890",
        email: "",
        ntn: "",
        address: "Circular Road, Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Rashid Hussian pic.jpg",
      },
      {
        membershipNo: "M No.836",
        firstName: "Saddique",
        lastName: "Blouch",
        fatherName: "Muhammad Yousuf",
        cnic: "42207-7890123-4",
        phone: "0323-7890123",
        email: "",
        ntn: "",
        address: "Old City, Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/saddique blouch pic.jpg",
      },
      {
        membershipNo: "M No.837",
        firstName: "Salman",
        lastName: "Sahri",
        fatherName: "Kareem Bux",
        cnic: "",
        phone: "0304-2834418",
        email: "",
        ntn: "",
        address: "Govt. High School Bachil Illanbhro District Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Student",
        fee: 0,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Salman Sahri pic.jpg",
      },
      {
        membershipNo: "M No.838",
        firstName: "Shoaib",
        lastName: "",
        fatherName: "Muhammad Lasheri Lasbari",
        cnic: "42201-9777571-9",
        phone: "0300-2144948",
        email: "",
        ntn: "",
        address: "Goth Lasheri Post Office Rasool Abad Peer Umar Shah Tehsil Sobodero District Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Shoaib pic.jpg",
      },
      {
        membershipNo: "M No.839",
        firstName: "Yar Muhamamd",
        lastName: "Mari Baloch",
        fatherName: "Karim Khan",
        cnic: "42208-8901234-5",
        phone: "0334-8901234",
        email: "",
        ntn: "",
        address: "Market Road, Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Yar Muhamamd Mari baloch pic.jpg",
      },
      {
        membershipNo: "M No.840",
        firstName: "Zafar",
        lastName: "",
        fatherName: "Muhbat Khan",
        cnic: "45206-2420591-7",
        phone: "0306-1232449",
        email: "",
        ntn: "",
        address: "Tando Mir Ali Village Soomharsam Taluka Thari Mir Wah District Khairpur",
        district: "Khairpur",
        businessName: "",
        businessType: "Vice Chairman Sukkur Division",
        membershipCategory: "Executive",
        fee: 5000,
        status: "Active",
        joinedDate: new Date("2024-01-01"),
        photo: "/uploads/Zafar pic.jpg",
      },
    ];

    await Member.insertMany(members);

    return NextResponse.json({ 
      success: true, 
      message: `Seeded ${members.length} members successfully` 
    });

  } catch (error) {
    console.error("Seed error:", error);
    return NextResponse.json({ error: "Seed failed" }, { status: 500 });
  }
}
