/**
 * Demo members shown when MongoDB is unavailable.
 * Photos use UI Avatars — a free, reliable service that generates
 * initials-based professional avatars with custom colours.
 * Replace with real photos once MongoDB is connected.
 */

export const DEMO_MEMBERS = [
  {
    _id: "demo_001",
    membershipNo: "CFA-2024-001",
    firstName: "Ahmed",
    lastName: "Raza",
    fatherName: "Muhammad Raza",
    cnic: "42101-1234567-1",
    phone: "+92 300 1234567",
    email: "ahmed.raza@agrofarm.pk",
    ntn: "1234567-8",
    address: "Plot 45, SITE Area, Karachi",
    district: "Karachi",
    businessName: "AgroFarm Pakistan Pvt Ltd",
    businessType: "Agricultural Farming",
    membershipCategory: "Corporate",
    fee: 30000,
    status: "Active",
    joinedDate: "2024-01-15",
    photo: "https://ui-avatars.com/api/?name=Ahmed+Raza&background=059669&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_002",
    membershipNo: "CFA-2024-002",
    firstName: "Sara",
    lastName: "Malik",
    fatherName: "Tariq Malik",
    cnic: "35202-9876543-2",
    phone: "+92 321 9876543",
    email: "sara.malik@greenfuture.pk",
    ntn: "9876543-2",
    address: "House 12, Model Town, Lahore",
    district: "Lahore",
    businessName: "Green Future Organics",
    businessType: "Organic Food Processing",
    membershipCategory: "Women",
    fee: 3000,
    status: "Active",
    joinedDate: "2024-02-20",
    photo: "https://ui-avatars.com/api/?name=Sara+Malik&background=e11d48&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_003",
    membershipNo: "CFA-2024-003",
    firstName: "Muhammad",
    lastName: "Farooq",
    fatherName: "Abdul Farooq",
    cnic: "61101-5554433-3",
    phone: "+92 333 5554433",
    email: "m.farooq@seedtech.pk",
    ntn: "5554433-9",
    address: "Grain Market, Multan Road, Faisalabad",
    district: "Faisalabad",
    businessName: "SeedTech Solutions",
    businessType: "Seed Distribution",
    membershipCategory: "Executive",
    fee: 5000,
    status: "Active",
    joinedDate: "2024-03-10",
    photo: "https://ui-avatars.com/api/?name=Muhammad+Farooq&background=2563eb&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_004",
    membershipNo: "CFA-2024-004",
    firstName: "Zainab",
    lastName: "Hussain",
    fatherName: "Ghulam Hussain",
    cnic: "38403-7778899-4",
    phone: "+92 345 7778899",
    email: "zainab.h@freshproduce.pk",
    ntn: "",
    address: "Village Chak 40, Multan",
    district: "Multan",
    businessName: "Fresh Produce Co.",
    businessType: "Fruits & Vegetables",
    membershipCategory: "Associate",
    fee: 2000,
    status: "Active",
    joinedDate: "2024-04-05",
    photo: "https://ui-avatars.com/api/?name=Zainab+Hussain&background=7c3aed&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_005",
    membershipNo: "CFA-2024-005",
    firstName: "Bilal",
    lastName: "Chaudhry",
    fatherName: "Arshad Chaudhry",
    cnic: "34101-2223334-5",
    phone: "+1 416 555 0199",
    email: "bilal.chaudhry@canagro.ca",
    ntn: "",
    address: "123 Maple Ave, Toronto, Canada",
    district: "Overseas",
    businessName: "CanAgro Exports Inc.",
    businessType: "Agricultural Export",
    membershipCategory: "Overseas",
    fee: 100,
    status: "Active",
    joinedDate: "2024-05-18",
    photo: "https://ui-avatars.com/api/?name=Bilal+Chaudhry&background=0284c7&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_006",
    membershipNo: "CFA-2024-006",
    firstName: "Ali",
    lastName: "Raza",
    fatherName: "Noor Raza",
    cnic: "42201-3334445-6",
    phone: "+92 311 3334445",
    email: "ali.raza@agristu.edu.pk",
    ntn: "",
    address: "University of Agriculture, Faisalabad",
    district: "Faisalabad",
    businessName: "UAF Agriculture Dept.",
    businessType: "Student",
    membershipCategory: "Student",
    fee: 0,
    status: "Active",
    joinedDate: "2024-06-01",
    photo: "https://ui-avatars.com/api/?name=Ali+Raza&background=d97706&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_007",
    membershipNo: "CFA-2024-007",
    firstName: "Dr. Nadia",
    lastName: "Siddiqui",
    fatherName: "Iqbal Siddiqui",
    cnic: "42301-6667778-7",
    phone: "+92 300 6667778",
    email: "dr.nadia@minfa.gov.pk",
    ntn: "",
    address: "Ministry of National Food Security, Islamabad",
    district: "Islamabad",
    businessName: "Ministry of National Food Security",
    businessType: "Government / Policy",
    membershipCategory: "Honorary Member",
    fee: 0,
    status: "Active",
    joinedDate: "2024-01-01",
    photo: "https://ui-avatars.com/api/?name=Nadia+Siddiqui&background=475569&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_008",
    membershipNo: "CFA-2024-008",
    firstName: "Kamran",
    lastName: "Butt",
    fatherName: "Saeed Butt",
    cnic: "35301-4445556-8",
    phone: "+92 323 4445556",
    email: "kamran@buttfarms.pk",
    ntn: "4445556-3",
    address: "Ravi Road, Lahore",
    district: "Lahore",
    businessName: "Butt Farms & Dairy",
    businessType: "Dairy & Livestock",
    membershipCategory: "Corporate",
    fee: 30000,
    status: "Active",
    joinedDate: "2024-07-22",
    photo: "https://ui-avatars.com/api/?name=Kamran+Butt&background=059669&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_009",
    membershipNo: "CFA-2024-009",
    firstName: "Fatima",
    lastName: "Zahra",
    fatherName: "Haider Zahra",
    cnic: "42401-8889990-9",
    phone: "+92 312 8889990",
    email: "fatima.z@spiceworld.pk",
    ntn: "8889990-1",
    address: "Spice Market, Old City, Hyderabad",
    district: "Hyderabad",
    businessName: "Spice World Exports",
    businessType: "Spice & Herb Trade",
    membershipCategory: "Women",
    fee: 3000,
    status: "Active",
    joinedDate: "2024-08-14",
    photo: "https://ui-avatars.com/api/?name=Fatima+Zahra&background=e11d48&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_010",
    membershipNo: "CFA-2024-010",
    firstName: "Usman",
    lastName: "Ghani",
    fatherName: "Abdul Ghani",
    cnic: "54400-1112223-0",
    phone: "+92 342 1112223",
    email: "usman@peshawarfoods.pk",
    ntn: "1112223-7",
    address: "Ring Road Industrial Area, Peshawar",
    district: "Peshawar",
    businessName: "Peshawar Foods Ltd",
    businessType: "Food Processing",
    membershipCategory: "Executive",
    fee: 5000,
    status: "Active",
    joinedDate: "2024-09-03",
    photo: "https://ui-avatars.com/api/?name=Usman+Ghani&background=2563eb&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_011",
    membershipNo: "CFA-2024-011",
    firstName: "Hina",
    lastName: "Nawaz",
    fatherName: "Nawaz Ahmad",
    cnic: "35404-2223334-1",
    phone: "+92 301 2223334",
    email: "hina.nawaz@ruralcraft.pk",
    ntn: "",
    address: "Gujranwala Road, Sialkot",
    district: "Sialkot",
    businessName: "Rural Craft Foods",
    businessType: "Cottage Industry",
    membershipCategory: "Women",
    fee: 3000,
    status: "Active",
    joinedDate: "2023-11-20",
    photo: "https://ui-avatars.com/api/?name=Hina+Nawaz&background=e11d48&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_012",
    membershipNo: "CFA-2024-012",
    firstName: "Imran",
    lastName: "Sheikh",
    fatherName: "Rafiq Sheikh",
    cnic: "42501-3334445-2",
    phone: "+44 20 7946 0321",
    email: "imran.sheikh@pakagro.co.uk",
    ntn: "",
    address: "22 Baker Street, London, UK",
    district: "Overseas",
    businessName: "PakAgro UK Ltd",
    businessType: "Import / Export",
    membershipCategory: "Overseas",
    fee: 100,
    status: "Active",
    joinedDate: "2024-10-11",
    photo: "https://ui-avatars.com/api/?name=Imran+Sheikh&background=0284c7&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_013",
    membershipNo: "CFA-2024-013",
    firstName: "Tariq",
    lastName: "Mehmood",
    fatherName: "Aslam Mehmood",
    cnic: "36302-5566778-3",
    phone: "+92 315 5566778",
    email: "tariq@punjabrice.pk",
    ntn: "5566778-4",
    address: "Rice Market, Gujranwala",
    district: "Gujranwala",
    businessName: "Punjab Rice Mills",
    businessType: "Rice Processing",
    membershipCategory: "Corporate",
    fee: 30000,
    status: "Active",
    joinedDate: "2024-03-28",
    photo: "https://ui-avatars.com/api/?name=Tariq+Mehmood&background=059669&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_014",
    membershipNo: "CFA-2024-014",
    firstName: "Amna",
    lastName: "Khan",
    fatherName: "Saleem Khan",
    cnic: "61301-9988776-4",
    phone: "+92 336 9988776",
    email: "amna.khan@herbpk.com",
    ntn: "",
    address: "Cantonment Area, Quetta",
    district: "Quetta",
    businessName: "HerbPK Botanicals",
    businessType: "Medicinal Herbs",
    membershipCategory: "Associate",
    fee: 2000,
    status: "Active",
    joinedDate: "2024-11-05",
    photo: "https://ui-avatars.com/api/?name=Amna+Khan&background=7c3aed&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_015",
    membershipNo: "CFA-2024-015",
    firstName: "Hassan",
    lastName: "Qureshi",
    fatherName: "Naeem Qureshi",
    cnic: "35501-7766554-5",
    phone: "+92 322 7766554",
    email: "hassan@qfarms.pk",
    ntn: "7766554-2",
    address: "Shahdara, Lahore",
    district: "Lahore",
    businessName: "Q Farms & Horticulture",
    businessType: "Horticulture",
    membershipCategory: "Executive",
    fee: 5000,
    status: "Active",
    joinedDate: "2024-12-01",
    photo: "https://ui-avatars.com/api/?name=Hassan+Qureshi&background=2563eb&color=fff&size=200&bold=true&format=png",
  },
  {
    _id: "demo_016",
    membershipNo: "CFA-2024-016",
    firstName: "Sana",
    lastName: "Iqbal",
    fatherName: "Iqbal Ahmed",
    cnic: "42601-4433221-6",
    phone: "+92 317 4433221",
    email: "sana.iqbal@agristu.edu.pk",
    ntn: "",
    address: "NED University, Karachi",
    district: "Karachi",
    businessName: "NED Agri Research",
    businessType: "Student",
    membershipCategory: "Student",
    fee: 0,
    status: "Active",
    joinedDate: "2024-08-22",
    photo: "https://ui-avatars.com/api/?name=Sana+Iqbal&background=d97706&color=fff&size=200&bold=true&format=png",
  },
];
